
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package miniJava.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int O_PAR = 19;
  public static final int C_BRACKET = 24;
  public static final int INTEGER = 45;
  public static final int GREATER = 31;
  public static final int INT = 7;
  public static final int O_BRACKET = 23;
  public static final int LESS = 29;
  public static final int MINUS = 34;
  public static final int STATIC = 5;
  public static final int SEMICOLON = 15;
  public static final int AND = 26;
  public static final int C_PAR = 20;
  public static final int OR = 25;
  public static final int BOOL = 8;
  public static final int COMMA = 17;
  public static final int CLASS = 2;
  public static final int DIV = 36;
  public static final int PLUS = 33;
  public static final int MAIN = 39;
  public static final int IF = 10;
  public static final int THIS = 13;
  public static final int ID = 46;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int ASS = 18;
  public static final int EQUAL = 27;
  public static final int TRUE = 44;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MOD = 37;
  public static final int VOID = 6;
  public static final int C_BRACE = 22;
  public static final int TIMES = 35;
  public static final int O_BRACE = 21;
  public static final int NEG = 38;
  public static final int G_EQUAL = 32;
  public static final int ELSE = 11;
  public static final int L_EQUAL = 30;
  public static final int N_EQUAL = 28;
  public static final int WHILE = 9;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 4;
  public static final int SYSO = 41;
  public static final int STRING = 40;
  public static final int FALSE = 43;
  public static final int LENGTH = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "EXTENDS",
  "STATIC",
  "VOID",
  "INT",
  "BOOL",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "THIS",
  "NEW",
  "SEMICOLON",
  "DOT",
  "COMMA",
  "ASS",
  "O_PAR",
  "C_PAR",
  "O_BRACE",
  "C_BRACE",
  "O_BRACKET",
  "C_BRACKET",
  "OR",
  "AND",
  "EQUAL",
  "N_EQUAL",
  "LESS",
  "L_EQUAL",
  "GREATER",
  "G_EQUAL",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "NEG",
  "MAIN",
  "STRING",
  "SYSO",
  "LENGTH",
  "FALSE",
  "TRUE",
  "INTEGER",
  "ID"
  };
}

